### ISSUE TITLE
text: accept bulk request

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/beard-server#10]
Since sending one author a time is very inefficient, `beard-server` should be able to accept a set of authors names to process. Thus the endpoint should accept `POST` request with `JSON` body containing a list of full names.

**Comment by jacenkow** [comment]
CC: @kaplun

**Comment by kaplun** [comment]
:+1: to be more precise this is related to the phonetic block interface.

Ideally the returned result should be a JSON dictionary so that it's possible to know what was mapped to what.

**Comment by jacenkow** [comment]
As an _option_, since we generate `uuid`s on `before_record_insert`, we already know them while dispatching to `beard-server`,  the returned dictionary could contain key representing signature's `uuid` and phonetic block as the value.

``` python
{'c19e97f1-7719-4640-97f8-7a9f30c01d23': 'CAPLANs'}
```

**Comment by kaplun** [comment]
If you pass the UUID in input as well yes. But I think it's not improving really the functionality, rather adding more data to transfer to the request and response...
